version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: national_championate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
